version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./k8s/mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "3000:3000"

volumes:
  mysql-data:
