apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-rollout
  namespace: production
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 30
        - pause: {duration: 3m}
        - setWeight: 60
        - pause: {duration: 3m}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: eshu786/backend
          ports:
            - containerPort: 3000
